name: Blog Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Hogo_Build:
    runs-on: windows-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - run: echo 正在构建博客
      - run: hugo
